#!/bin/bash

foamLog simpleFoam.out >/dev/null ### extract the useful information from the log file

gnuplot -persist > /dev/null 2>&1 << EOF
	set terminal enhanced font '"Times New Roman, 10' linewidth 2
	set terminal png size 925, 625
	set output "Convergence.png"
        set logscale y
        set title "Residual vs. Iteration"
        set xlabel "Iteration"
        set ylabel "Residual"
        set format y "%1.0e"
        set grid
        plot	"logs/Ux_0" with lines,\
        		"logs/Uy_0" with lines,\
        		"logs/Uz_0" with lines,\
        		"logs/p_0" with lines,\
        		"logs/k_0" with lines,\
				"logs/omega_0" with lines,\
        		"logs/epsilon_0" with lines
EOF

